spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  graphql:
    schema:
      locations: classpath:graphql/**/

balanced:
  encryption:
    key: YmFsYW5jZWQtdGVzdC1lbmNyeXB0aW9uLWtleS0zMmI=
  aggregation:
    provider: teller
