info:
  name: PATCH
  type: http
  seq: 1

http:
  method: PATCH
  url: "{{dripl-base-url}}/api/v1/budgets/:budgetId/categories/:categoryId"
  params:
    - name: budgetId
      value: edf6cc40-1433-4f06-a82e-5a3d50b029cb
      type: path
    - name: categoryId
      value: 794b548b-da04-496e-a8bc-cea4a08436ae
      type: path
  body:
    type: json
    data: |-
      {
          "rolloverType": "AVAILABLE_POOL"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
